#if !canImport(ObjectiveC)
import XCTest

extension URLRequest_AWSTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__URLRequest_AWSTests = [
        ("testCanonicalRequest", testCanonicalRequest),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(URLRequest_AWSTests.__allTests__URLRequest_AWSTests),
    ]
}
#endif
